# fly.toml app configuration file generated for reuron-grace on 2023-05-08T16:24:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reuron-grace"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "grace-server:hcks2r9s2s286wf76pq98n8dmkrbm24m"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
