name: Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: reuron
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Bump reuron version
        run: nix flake lock --update-input reuron
      - name: Build server container
        run: nix build .#server-container
      - name: Load server container
        run: docker load < result
      - name: Deploy to fly.io
        run: flyctl deploy --local-only
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
